# Generated by Django 6.0.2 on 2026-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calorieapp", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="calorie_goal",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
